apiVersion: v2
name: capp-monitoring
description: >
  Benchmarking suite for CAPP and Knative.
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: benchmarks
    version: "0.1.0"
    condition: "benchmarks.enabled"
