{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-benchmark-scripts
  labels: {{ include "benchmarks.labels" . | nindent 4 }}
data:
  load.js: |
{{ .Files.Get "files/scale/load.js" | indent 4 }}
  scale-test.sh: |
{{ .Files.Get "files/scale/scale-test.sh" | indent 4 }}
{{- end }}
