enabled: true

image:
  repository: ghcr.io/dana-team/capp-status-server
  tag: "0.1.0"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  port: 8080

namespaces:
  capp: capp-system
  knative: knative-serving
  certManager: cert-manager
  logging: logging-operator
  nfspvc: nfspvc-operator
  providerDns: provider-dns

serviceMonitor:
  enabled: true
  interval: 30s
  labels: {}
